#! /bin/sh
echo autoheader...
autoheader
echo libtoolize...
libtoolize -c -f
echo aclocal...
aclocal -I m4
echo automake...
automake -c -a &&
echo autoconf...
autoconf
echo "Now run configure with any arguments necessary"
